/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRunRouteImport } from './routes/api/run'
import { Route as ApiLessonsIndexRouteImport } from './routes/api/lessons/index'
import { Route as ApiLessonsSlugRouteImport } from './routes/api/lessons/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunRoute = ApiRunRouteImport.update({
  id: '/api/run',
  path: '/api/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLessonsIndexRoute = ApiLessonsIndexRouteImport.update({
  id: '/api/lessons/',
  path: '/api/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLessonsSlugRoute = ApiLessonsSlugRouteImport.update({
  id: '/api/lessons/$slug',
  path: '/api/lessons/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/run': typeof ApiRunRoute
  '/api/lessons/$slug': typeof ApiLessonsSlugRoute
  '/api/lessons': typeof ApiLessonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/run': typeof ApiRunRoute
  '/api/lessons/$slug': typeof ApiLessonsSlugRoute
  '/api/lessons': typeof ApiLessonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/run': typeof ApiRunRoute
  '/api/lessons/$slug': typeof ApiLessonsSlugRoute
  '/api/lessons/': typeof ApiLessonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/run' | '/api/lessons/$slug' | '/api/lessons'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/run' | '/api/lessons/$slug' | '/api/lessons'
  id: '__root__' | '/' | '/api/run' | '/api/lessons/$slug' | '/api/lessons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRunRoute: typeof ApiRunRoute
  ApiLessonsSlugRoute: typeof ApiLessonsSlugRoute
  ApiLessonsIndexRoute: typeof ApiLessonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/run': {
      id: '/api/run'
      path: '/api/run'
      fullPath: '/api/run'
      preLoaderRoute: typeof ApiRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lessons/': {
      id: '/api/lessons/'
      path: '/api/lessons'
      fullPath: '/api/lessons'
      preLoaderRoute: typeof ApiLessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lessons/$slug': {
      id: '/api/lessons/$slug'
      path: '/api/lessons/$slug'
      fullPath: '/api/lessons/$slug'
      preLoaderRoute: typeof ApiLessonsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRunRoute: ApiRunRoute,
  ApiLessonsSlugRoute: ApiLessonsSlugRoute,
  ApiLessonsIndexRoute: ApiLessonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
